const data = [
  { day: 1, allowance: null, needs: null, wants: null, savings: null },
  { day: 2, allowance: null, needs: null, wants: null, savings: null },
  { day: 3, allowance: null, needs: null, wants: null, savings: null },
  { day: 4, allowance: null, needs: null, wants: null, savings: null },
  { day: 5, allowance: null, needs: null, wants: null, savings: null },
  { day: 6, allowance: null, needs: null, wants: null, savings: null },
  { day: 7, allowance: null, needs: null, wants: null, savings: null },
  { day: 8, allowance: null, needs: null, wants: null, savings: null },
  { day: 9, allowance: null, needs: null, wants: null, savings: null },
  { day: 10, allowance: null, needs: null, wants: null, savings: null },
  { day: 11, allowance: null, needs: null, wants: null, savings: null },
  { day: 12, allowance: null, needs: null, wants: null, savings: null },
  { day: 13, allowance: null, needs: null, wants: null, savings: null },
  { day: 14, allowance: null, needs: null, wants: null, savings: null },
  { day: 15, allowance: null, needs: null, wants: null, savings: null },
  { day: 16, allowance: null, needs: null, wants: null, savings: null },
  { day: 17, allowance: null, needs: null, wants: null, savings: null },
  { day: 18, allowance: null, needs: null, wants: null, savings: null },
  { day: 19, allowance: null, needs: null, wants: null, savings: null },
  { day: 20, allowance: null, needs: null, wants: null, savings: null },
  { day: 21, allowance: null, needs: null, wants: null, savings: null },
  { day: 22, allowance: null, needs: null, wants: null, savings: null },
  { day: 23, allowance: null, needs: null, wants: null, savings: null },
  { day: 24, allowance: null, needs: null, wants: null, savings: null },
  { day: 25, allowance: null, needs: null, wants: null, savings: null },
  { day: 26, allowance: null, needs: null, wants: null, savings: null },
  { day: 27, allowance: null, needs: null, wants: null, savings: null },
  { day: 28, allowance: null, needs: null, wants: null, savings: null },
  { day: 29, allowance: null, needs: null, wants: null, savings: null },
  { day: 30, allowance: null, needs: null, wants: null, savings: null },
];

export default data;
